### ISSUE TITLE
new dæmonmap rebased on q3map2

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/daemonmap#2]
Hi, I just pushed a new branch named `daemonmap`, its purpose is to become the `master` branch and let the current `master` one renamed to something like `legacy`.

This daemonmap source is Fuma's code rebased applied on current NetRadiant master tree. Everything else that was not required was deleted, including `netradiant` itself and out of topic tools like `q3data`, and  functionalities from q3map2 like bsp compilation, bsp analysis, bsp scaling, bsp conversion, vis computation, lightmap rendering, and everything else but the navmesh code was deleted so people can't build a map with daemonmap by mistake: daemonmap only knows how to compute navmeshes.

Despite of the deletion of lot of files the file layout from NetRadiant tree was kept to allow future code exchange if required.

This tool is made to be deleted one day because the only way for a game project to have proper navmeshes after having changed model size or added or removed models is to get navmeshes produced by engine using game code settings. That's why there is no effort to merge this code into NetRadiant upstream since this tool must be considered as a temporary hack.

The code shrink may also help an engine contributor to find more easily what have to be moved back to engine.

This tree enable daemonmap with more modern behaviours like the abilities to be driven by build tools properly and to make out of tree builds. The online help is also available.

This tree use recastnavigation as a submodule, upgrading it to the one currently used by the Dæmon engine itself: the commit just before the daemon assert customization.

To use recastnavigation upstream some assert code must be written before, see https://github.com/DaemonEngine/Daemon/pull/130 for similar issue on engine side.

I have not yet tested produced navmeshes in game.

**Comment by illwieckz** [comment]
Bots fighting in `starport` map on navmeshes produced by this branch:

[![starport](https://dl.illwieckz.net/b/unvanquished/shots/maps/starport/unvanquished_2018-10-26_010353_000.jpg)](https://dl.illwieckz.net/b/unvanquished/shots/maps/starport/unvanquished_2018-10-26_010353_000.jpg)

It works.

**Comment by illwieckz** [comment]
I have just synced the botlib code with daemon tree, so now daemonmap and daemon use same detour/recast/botlib code.

**Comment by DolceTriade** [comment]
Very cool!

**Comment by illwieckz** [comment]
I also moved copypasted code from `daemon:src/common/cm/cm_patch.cpp` that was lying in `daemonmap:tools/quake3/q3map2/nav.cpp` in a new `daemonmap:libs/cm/cm_patch.cpp` (with related header) file and added an `#include cm_patch.cpp` in `nav.cpp`, this way it would make the re-inclusion in daemon tree easier later. I haven't not synced with current `cm_patch.cpp` because it would pull too much headers, almost everything, and making daemon a submodule because of one file would be too much.

To be able to use latest `botlib` code I had to imprt `Compiler.h` from engine.

Well, that navmesh code is full of engine code, I hope one day it will live within engine code and be run by engine at game time!

**Comment by illwieckz** [comment]
Note that I included the history that was sitting in `Unvanquished` repository _before_ the extraction of `daemonmap`.

**Comment by illwieckz** [comment]
I did the branch switch: the legacy code is now in… well the `legacy` branch. The `master` branch is now the new tree rebased on NetRadiant, replaying commits from Unvanquished, rebasing commits from the legacy branch, syncing botlib, recast, navmesh and so on.
